# basic options
title: My Awesome Blog
author: Michael Cunnane 
email: your-email@domain.com
description: Everything about me, really!
twitter_username: jekyllrb
github_username:  smileymike

# Build settings
markdown: kramdown
theme: minima
